name: flutter_env
description: "A plugin/utility that provides compile-time variables for native platforms."
version: 0.0.1
homepage: https://github.com/Mastersam07/flutter_env
repository: https://github.com/Mastersam07/flutter_env
issue_tracker: https://github.com/Mastersam07/flutter_env/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tech.mastersam.flutter_env
        pluginClass: FlutterEnvPlugin
      ios:
        pluginClass: FlutterEnvPlugin
